# Generated by Django 4.2.1 on 2023-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robustness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.CharField(default='usr', max_length=50),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterModelTable(
            name='img',
            table='imgtest',
        ),
    ]
