# Generated by Django 4.2.2 on 2023-06-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robustness', '0002_img_name_alter_img_img_alter_img_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterModelTable(
            name='img',
            table=None,
        ),
    ]
